lib/petsposts_web/router.ex
defmodule PetspostsWeb.Router do
  use PetspostsWeb, :router
  alias Phoenix.Controller

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :api_auth
  end

  scope "/api", PetspostsWeb do
    pipe_through :api

    resources "/posts", PostApiController, only: [:create, :index, :show]
  end

  scope "/", PetspostsWeb do
    pipe_through :browser

    resources "/", PostController, only: [:create, :index, :show]
  end

  defp current_user(conn, _ ) do
    assign(conn, :current_user, Petsposts.Accounts.current_user)
  end

  defp api_auth(conn, _) do
    token = Application.get_env(:petsposts, :api_auth_token)
    case  get_req_header(conn, "auth-token") do
      [^token] ->
        conn

      _ ->
        conn
        |> put_status(401)
        |> Controller.render(PetspostsWeb.ErrorView, "401.json")
        |> halt()
    end
  end

end

lib/petsposts_web/views/layout_view.ex
defmodule PetspostsWeb.LayoutView do
  use PetspostsWeb, :view
end

lib/petsposts_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Petsposts · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <%= render "navbar.html", assigns %>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/petsposts_web/templates/layout/navbar.html.eex
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="<%= Routes.post_path(@conn, :index) %>">
        Home
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Order
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item" href="<%= PetspostsWeb.PostView.path(@conn, order_by: :inserted_at) %>">
            Date
          </a>
          <a class="navbar-item" href="<%= PetspostsWeb.PostView.path(@conn, order_by: :likes) %>">
            Likes
          </a>
          <a class="navbar-item" href="<%= PetspostsWeb.PostView.path(@conn, order_by: :views) %>">
            Views
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item" href="<%=  PetspostsWeb.PostView.path(@conn, order_dir: PetspostsWeb.PostView.next_order_dir(@conn))%>">
            <%= PetspostsWeb.PostView.current_order_dir(@conn) %>
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>